#!/usr/bin/python3

import os
import datetime

print("Content-Type: text/html\n")
print("<!DOCTYPE html>")
print("<html>")
print("<head>")
print("    <title>Python CGI Test</title>")
print("    <style>")
print("        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; background-color: #f5f5f5; }")
print("        .container { background-color: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }")
print("        h1 { color: #333; border-bottom: 3px solid #4CAF50; padding-bottom: 10px; }")
print("        .success { color: #4CAF50; font-weight: bold; }")
print("        table { width: 100%; border-collapse: collapse; margin: 20px 0; }")
print("        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }")
print("        th { background-color: #4CAF50; color: white; }")
print("        a { color: #4CAF50; text-decoration: none; }")
print("        a:hover { text-decoration: underline; }")
print("    </style>")
print("</head>")
print("<body>")
print("    <div class='container'>")
print("        <h1>Python CGI Test</h1>")
print("        <p class='success'>SUCCESS! Python CGI is working correctly.</p>")
print("        <h2>Server Information</h2>")
print("        <table>")
print("            <tr><th>Variable</th><th>Value</th></tr>")
print("            <tr><td>Current Time</td><td>" + str(datetime.datetime.now()) + "</td></tr>")
print("            <tr><td>SERVER_SOFTWARE</td><td>" + os.environ.get('SERVER_SOFTWARE', 'N/A') + "</td></tr>")
print("            <tr><td>SERVER_NAME</td><td>" + os.environ.get('SERVER_NAME', 'N/A') + "</td></tr>")
print("            <tr><td>GATEWAY_INTERFACE</td><td>" + os.environ.get('GATEWAY_INTERFACE', 'N/A') + "</td></tr>")
print("            <tr><td>REQUEST_METHOD</td><td>" + os.environ.get('REQUEST_METHOD', 'N/A') + "</td></tr>")
print("            <tr><td>QUERY_STRING</td><td>" + os.environ.get('QUERY_STRING', 'N/A') + "</td></tr>")
print("            <tr><td>REMOTE_ADDR</td><td>" + os.environ.get('REMOTE_ADDR', 'N/A') + "</td></tr>")
print("            <tr><td>HTTP_USER_AGENT</td><td>" + os.environ.get('HTTP_USER_AGENT', 'N/A') + "</td></tr>")
print("        </table>")
print("        <p><a href='/'>Back to Home</a></p>")
print("    </div>")
print("</body>")
print("</html>")
