#!/usr/bin/perl

print "Content-Type: text/html\n\n";
print "<!DOCTYPE html>\n";
print "<html>\n";
print "<head>\n";
print "    <title>Perl CGI Test</title>\n";
print "    <style>\n";
print "        body { font-family: Arial, sans-serif; max-width: 800px; margin: 50px auto; padding: 20px; background-color: #f5f5f5; }\n";
print "        .container { background-color: white; padding: 30px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }\n";
print "        h1 { color: #333; border-bottom: 3px solid #4CAF50; padding-bottom: 10px; }\n";
print "        .success { color: #4CAF50; font-weight: bold; }\n";
print "        table { width: 100%; border-collapse: collapse; margin: 20px 0; }\n";
print "        th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }\n";
print "        th { background-color: #4CAF50; color: white; }\n";
print "        a { color: #4CAF50; text-decoration: none; }\n";
print "        a:hover { text-decoration: underline; }\n";
print "    </style>\n";
print "</head>\n";
print "<body>\n";
print "    <div class='container'>\n";
print "        <h1>Perl CGI Test</h1>\n";
print "        <p class='success'>SUCCESS! Perl CGI is working correctly.</p>\n";
print "        <h2>Server Information</h2>\n";
print "        <table>\n";
print "            <tr><th>Variable</th><th>Value</th></tr>\n";
print "            <tr><td>Current Time</td><td>" . localtime() . "</td></tr>\n";
print "            <tr><td>Perl Version</td><td>$]</td></tr>\n";
print "            <tr><td>SERVER_SOFTWARE</td><td>" . ($ENV{'SERVER_SOFTWARE'} || 'N/A') . "</td></tr>\n";
print "            <tr><td>SERVER_NAME</td><td>" . ($ENV{'SERVER_NAME'} || 'N/A') . "</td></tr>\n";
print "            <tr><td>GATEWAY_INTERFACE</td><td>" . ($ENV{'GATEWAY_INTERFACE'} || 'N/A') . "</td></tr>\n";
print "            <tr><td>REQUEST_METHOD</td><td>" . ($ENV{'REQUEST_METHOD'} || 'N/A') . "</td></tr>\n";
print "            <tr><td>QUERY_STRING</td><td>" . ($ENV{'QUERY_STRING'} || 'N/A') . "</td></tr>\n";
print "            <tr><td>REMOTE_ADDR</td><td>" . ($ENV{'REMOTE_ADDR'} || 'N/A') . "</td></tr>\n";
print "            <tr><td>HTTP_USER_AGENT</td><td>" . ($ENV{'HTTP_USER_AGENT'} || 'N/A') . "</td></tr>\n";
print "        </table>\n";
print "        <p><a href='/'>Back to Home</a></p>\n";
print "    </div>\n";
print "</body>\n";
print "</html>\n";
